baseURL = "https://kenberkeley.github.io/"
theme = "ananke"

defaultContentLanguage = "zh"
hasCJKLanguage = true
enableGitInfo = true

[languages]
[languages.zh]
weight = 0
title  = "土澳码农"
languageCode = "zh"
languageName = "简体中文"

[languages.en]
weight = 1
title = "Aussie Coder"
languageCode = "en"
languageName = "English"
